### ISSUE TITLE
Android 8 Connection problems

### ISSUE THREAD

**Issue by hrvylein** [GitHelge/resimulate#1]
Hey,
it seems, as if there is a connection problem on Android 10 devices.

A10 can't see Trainee devices running on A9, A9 Trainer can see A10 Trainee but can't connect.

Tested on Xiaomi (A10), Pixel 3 (A10) and Samsung tablet (A9).

Thanks in advance!

**Comment by hrvylein** [comment]
Maybe ACCESS_COARSE_LOCATION is causing it. ACCESS_FINE_LOCATION is needed for BLE scanning in A10.

**Comment by hrvylein** [comment]
Yup, that fixes the problem. Maybe you can update the app in the app store?

https://github.com/GitHelge/resimulate/pull/2

**Comment by GitHelge** [comment]
Hey, i updated the source here. Could you try the updated version? I don't have an Android 10 device and the simulator is not ideal to test wifi/bluetooth connections ;-)
If it works fine with my changes, I will upload the version to the store

Thanks for the pull request anyway, I added it myself in the process. :)

When you test the changes, please also check if the permission handler still works. I had to adapt it for Android 10 devices. [StartupActivity.kt Diff](https://github.com/GitHelge/resimulate/commit/a224c490af05599ba3ca3459925175dabee25943#diff-fbaec3d38f6e938d9dd7eae329ef0f99)

**Comment by hrvylein** [comment]
No Problem, your solution is far more superior. Going to test it after work. And give you feedback.

**Comment by hrvylein** [comment]
Compiles, finds and connects to other running installation of resimulate from A10 -> A9 and vice versa.

**Comment by GitHelge** [comment]
I tested on two non Android 10 devices myself and it seems to work fine, so I pushed the release build to the store. 🤞😅

**Comment by hrvylein** [comment]
Sorry to reopen. Now there is a problem with Android 8 devices.
Start app -> Trainee -> the app has permissions granted, the screen says the app needs access to a coarse location is displayed. Clicking ok, dismisses the message, but the app won't enter the search for trainer state, as a snackbar will tell me access to coarse location is needed.

I reinstalled the app, pressed OK, permission window pops up, permission gets granted, same error. I checked the permissions in the app management but everything is okay.

**Comment by hrvylein** [comment]
My quick & dirty pr raises the same problem on Android 8. Trainermode on Android 8 "works" despite getting the snackbar message and connection takes a long time to establish.

**Comment by GitHelge** [comment]
Will took at it tonight. Sorry for the inconvinience

**Comment by GitHelge** [comment]
Could be that i previously implemented a bug for many older devices: (This should fix it) Dunno if it fixes the Android 8 Bug though. https://github.com/GitHelge/resimulate/commit/9a3808c75ee6fb8dda815269b544edd580de0c91

**Comment by hrvylein** [comment]
Still gives the same error. I think needPermissions() was calling the wrong permission check for the coressponding api level. I changed that, compiled and it works. Added a PR.

https://github.com/GitHelge/resimulate/pull/4

**Comment by GitHelge** [comment]
Thank you, I must have messed the condition up. 😅

**Comment by GitHelge** [comment]
I merged your pr and pushed the new build to the store. I would be glad if you could test its functionality too :)

**Comment by hrvylein** [comment]
Just tested it and it works!
